window.RIDEZ_CONFIG = {
  SUPABASE_URL: "PASTE_YOUR_SUPABASE_URL_HERE",
  SUPABASE_ANON_KEY: "PASTE_YOUR_SUPABASE_ANON_KEY_HERE",
  STATIONARY_SECONDS: 3,
  MOVING_THRESHOLD_MS: 2.5,
  STOPPED_THRESHOLD_MS: 0.8,
  LOCATION_UPLOAD_MS: 3000,
  MESSAGE_POLL_MS: 3000
};
