window.RIDEZ_CONFIG = {
SUPABASE_URL: "https://bfevmnwnebnyadclhlwx.supabase.co",
 SUPABASE_ANON_KEY: "sb_publishable_F0NrPaSbt3WX_zDO2BPQqA_4JLkLJyA",
  STATIONARY_SECONDS: 3,
  MOVING_THRESHOLD_MS: 2.5,
  STOPPED_THRESHOLD_MS: 0.8,
  LOCATION_UPLOAD_MS: 3000,
  MESSAGE_POLL_MS: 3000
};
